using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum BlockTypes 
{
    E_BLOCK_NOTHING,
    E_BLOCK_AIR,
    E_BLOCK_GRASS_DIRT,
    E_BLOCK_DIRT,
    E_BLOCK_STONE,
    E_BLOCK_OAK_WOOD,
    E_BLOCK_COAL_ORE,
    E_BLOCK_IRON_ORE,
    E_BLOCK_OAK_LEAF,
    E_BLOCK_SAND,
    E_BLOCK_BADLANDS_SAND,
    E_BLOCK_CACTUS,
    E_BLOCK_WATER,
    E_BLOCK_GLASS,
    E_BLOCK_ICE,
    E_BLOCK_SAVANNAH_GRASS_DIRT,
    E_BLOCK_SPRUCE_WOOD,
    E_BLOCK_SPRUCE_LEAF,
    E_BLOCK_TAIGA_GRASS_DIRT,
    E_BLOCK_TAIGA_DIRT,
    E_BLOCK_SNOW,
    E_BLOCK_GRASS_BLADE,
    E_BLOCK_TULLIP,
    E_BLOCK_DANDELION,
    E_BLOCK_DAISY,
    E_BLOCK_COBBLESTONE,
    E_BLOCK_VINY_STONE,
    E_BLOCK_MOSSY_COBBLESTONE,
    E_BLOCK_FLOWER_LEAF,
    E_BLOCK_RED_BRICK,
}
